In [2]:
import numpy as np

In [3]:
# Slower
x = [1,2,3]
y = [4,5,6]
z = []
for list_1,list_2 in zip(x,y):
    zz = list_1+list_2
    z.append(zz)
print(z)

[5, 7, 9]


In [4]:
# Faster
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.add(x,y)
print(z)

[5 7 9]


In [5]:
print(f"Subtraction\na-b:{y-x}\nnp.subtract: {np.subtract(y,x)}")

Subtraction
a-b:[3 3 3]
np.subtract: [3 3 3]


In [ ]:
# Unary negation
np.negative(x)

array([-1, -2, -3])

In [7]:
np.multiply(x,y)

array([ 4, 10, 18])

In [8]:
np.divide(y,x)

array([4. , 2.5, 2. ])

In [9]:
np.floor_divide(y,x)

array([4, 2, 2])

In [10]:
np.power(x,y)

array([  1,  32, 729])

In [13]:
np.mod(y,x)

array([0, 1, 0])

Aggregate functions

In [18]:
l = np.arange(10)
print(l)
print(np.sum(l))

[0 1 2 3 4 5 6 7 8 9]
45


In [20]:
L = np.random.randint(0,100,100)
print(L)

[ 6 32 34 55 41 40 67 16 21 25 28  0 97 70 19 82 61 20 60 51 52 21 63 41
 59 24 18 27  2 62  1 84 98 22 23 58 77 20 60 74 42 55 22 26 23 89 11 68
 29 65 50 10 10 98 54 91 89 72 11 31 54 57 59 82  8 44 13 95 64 92 54 39
 81 16 58 82 56 72 65 87  1 68 85 74 20 15 40 27 67 43 65 88 29 96 95  4
 28 67 86  7]


In [22]:
big_array = np.random.rand(1000000)
print(big_array)

[0.76969744 0.36248326 0.89100414 ... 0.00112614 0.33345669 0.856575  ]


In [23]:
%timeit np.sum(big_array)

378 μs ± 23.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [24]:
%timeit sum(big_array)

44.1 ms ± 970 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%timeit min(big_array)

30.4 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%timeit np.min(big_array)

201 μs ± 16.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Multi dimesnional aggreagates

In [29]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print(M.sum(axis=0)) # Column sum
print(M.sum(axis=1)) # Row sum

[12 15 18]
[ 6 15 24]


In [ ]:
x = np.arange(1000000)
print(np.std(x)) # Standard Deviation
print(x.std())
print(x)

288675.1345946685
288675.1345946685
[     0      1      2 ... 999997 999998 999999]


Broadcasting

In [50]:
a = np.array([1,2,3])
b = 5
a + b


array([6, 7, 8])

In [54]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([10,20,30])
print(a)
print(b)

z = a + b
print(z)

[[1 2 3]
 [3 4 5]]
[10 20 30]
[[11 22 33]
 [13 24 35]]


In [55]:
print(a.shape)
print(b.shape)
print(z.shape)

(2, 3)
(3,)
(2, 3)


In [59]:
a = np.arange(3).reshape(3,1)
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [60]:
c = a + b
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.arange(4)
a + b

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 