In [4]:
import random
import numpy as np

In [ ]:
x = "four"

In [5]:
Mixed_list = [1,"4",3.5]
Mixed_list

[1, '4', 3.5]

In [9]:
type(Mixed_list[0])

int

In [10]:
import array

Fixed type Arrays

In [12]:
l1 = list(range(10))
Array1 = array.array("i", l1)
Array1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.array(l1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array([2,4.9,2.0])

array([2. , 4.9, 2. ])

Multi Dimnesional Array

A 2D array is like a table(rows and columns)

In [17]:
aar2 = np.array([[1,2,3],[4,5,6]])

In [18]:
aar2.shape

(2, 3)

A 3D array is like a stack of 2D arrays - Multiple pages or layers

In [21]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
a.shape

(1, 3, 3)

In [27]:
e  = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(e)
print(e.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


Creatinng arrays from scratch

In [28]:
# An array with integers filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# An array with integers filled with ones
a = np.ones([3,5], dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Filling arrays with values that are not ones or zeros

In [34]:
value = np.full((2,3),3.5) 
print(value)

[[3.5 3.5 3.5]
 [3.5 3.5 3.5]]


Array of values spaced between zero and one

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array of randomly distributed values between 0 and 10

In [ ]:
np.random.randint(10, size=(2,5))

array([[2, 1, 2, 8, 5],
       [3, 4, 9, 5, 2]], dtype=int32)

Random Floats between 0 and 1 using shape

In [70]:
np.random.random((3,3))

array([[0.66874759, 0.07874528, 0.21790834],
       [0.48318689, 0.50934703, 0.26627924],
       [0.86892519, 0.94919202, 0.58895925]])

In [95]:
np.random.randint(11, size=(3,3))

array([[2, 2, 1],
       [3, 4, 9],
       [1, 9, 3]], dtype=int32)

Create a 3x3 indentity matrix

In [97]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

NumPy array attributes

In [138]:
# 1-D array
x1 = np.random.randint(11, size=10)

# 2-D array
x2 = np.random.randint(10, size=(3,4))

# 3-D array
x3 = np.random.randint(10, size=(2,3,4))
print(x1)
print(x2)
print(x3)

[9 1 7 4 4 3 4 7 3 7]
[[9 0 3 8]
 [4 0 9 6]
 [8 2 7 9]]
[[[8 2 6 4]
  [3 2 1 6]
  [0 8 5 1]]

 [[6 4 6 9]
  [9 8 7 8]
  [4 2 0 4]]]


Getting properties of array

In [120]:
print("x1 dimensions: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)
print("x1 type: ", x1.dtype)

x1 dimensions:  1
x1 shape:  (10,)
x1 size:  10
x1 type:  int32


In [121]:
print("x2 dimensions: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)
print("x2 type: ", x2.dtype)

x2 dimensions:  2
x2 shape:  (3, 4)
x2 size:  12
x2 type:  int32


Array indexing (1-D)

In [139]:
x1

array([9, 1, 7, 4, 4, 3, 4, 7, 3, 7], dtype=int32)

In [140]:
print(x1[3])


4


In [141]:
print(x1[::-1])

[7 3 7 4 3 4 4 7 1 9]


Array Indexing (2-D)

In [143]:
x2

array([[9, 0, 3, 8],
       [4, 0, 9, 6],
       [8, 2, 7, 9]], dtype=int32)

In [144]:
print(x2[0,2]) # Specific values
print(x2[1]) # Specific row
print(x2[:,0]) # Specific column

3
[4 0 9 6]
[9 4 8]


In [148]:
x2[0,1] = 1
x2

array([[9, 1, 3, 8],
       [4, 0, 9, 6],
       [8, 2, 7, 9]], dtype=int32)

Array Slicing (1-D)

In [149]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [157]:
print(x[:5])

[0 1 2 3 4]


Array slicing (2-D)

In [156]:
print(x[::2])

[0 2 4 6 8]


Access first two rows and first 3 columns (2-D)

In [158]:
x2

array([[9, 1, 3, 8],
       [4, 0, 9, 6],
       [8, 2, 7, 9]], dtype=int32)

In [159]:
print(x2[:2, :3])

[[9 1 3]
 [4 0 9]]


In [163]:
print(x2[:2,1:3])

[[1 3]
 [0 9]]
