In [24]:
import numpy as np
import random

Masking with 1-D array

In [5]:
arr = np.array([10,20,30,40,50])
mask = arr > 25

result = arr[mask]
print(arr)
print(result)

[10 20 30 40 50]
[30 40 50]


In [7]:
arr = np.arange(10)
mask = arr > 5
result = arr[mask]
print(arr)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


Masking with 2-D arrays

In [9]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
mask2d = arr2d > 5
print(arr2d[mask2d])

[6 7 8 9]


Replacing values

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[arr < 7] = 0
print(arr)

[0 0 0 0 0 0 0 7 8 9]


Comparison Operator

In [17]:
x = np.arange(1,7)
print(x)

[1 2 3 4 5 6]


In [16]:
print(x > 3)
print(x[x > 3])

[False False False  True  True  True]
[4 5 6]


In [18]:
print(x != 3)
print(x[x != 3])

[ True  True False  True  True  True]
[1 2 4 5 6]


In [21]:
x * 2

array([ 2,  4,  6,  8, 10, 12])

In [22]:
x ** 2

array([ 1,  4,  9, 16, 25, 36])

In [23]:
(2 *x) == (x ** 2)

array([False,  True, False, False, False, False])

In [40]:
np.random.seed(42)
x = np.random.randint(1,11,(3,4))
print(x)

[[ 7  4  8  5]
 [ 7 10  3  7]
 [ 8  5  4  8]]


In [41]:
mask = x > 6
print(mask)
print(x[mask])

[[ True False  True False]
 [ True  True False  True]
 [ True False False  True]]
[ 7  8  7 10  7  8  8]


Counting entries

In [42]:
print(np.count_nonzero(x < 6))

5


In [ ]:
np.sum(x < 7)

np.int64(5)

In [47]:
print(np.count_nonzero(x < 6,  axis = 0))

[0 2 2 1]


In [45]:
np.any(x >8)

np.True_

In [49]:
x

array([[ 7,  4,  8,  5],
       [ 7, 10,  3,  7],
       [ 8,  5,  4,  8]], dtype=int32)

In [48]:
np.all(x < 10)

np.False_

In [50]:
np.all(x < 8, axis = 1)

array([False, False, False])

Boolean Operators

In [51]:
y = np.array([10,15,20,25,30,35,40])
print(y)

[10 15 20 25 30 35 40]


In [54]:
mask = y > 30
result = y[mask]
print(result)
print(y)

[35 40]
[10 15 20 25 30 35 40]


In [ ]:
z = (y > 15) & (y < 30)
print(y[z])

[20 25]


In [57]:
z = (y<15)|(y > 25)
print(y[z])

[10 30 35 40]


Fancy Indexing

In [59]:
F = np.random.randint(1,50,size=(5,))

In [61]:
F[[0,2,4]]

array([44, 38, 21], dtype=int32)

In [64]:
x

array([[ 7,  4,  8,  5],
       [ 7, 10,  3,  7],
       [ 8,  5,  4,  8]], dtype=int32)

In [63]:
# Select the element at postion (0,0), (1,1), (2,2)
x[[0,1,2], [0,1,2]]

array([ 7, 10,  4], dtype=int32)

In [67]:
x[1:3,[1,3]]

array([[10,  7],
       [ 5,  8]], dtype=int32)

In [71]:
x[:,[1,3]]

array([[ 4,  5],
       [10,  7],
       [ 5,  8]], dtype=int32)

In [80]:
row = np.array([1,2])
col = np.array([0,1])

x[np.ix_(row,col)]

array([[ 7, 10],
       [ 8,  5]], dtype=int32)

In [79]:
arr = np.array([4,1,5])
sorted = np.sort(arr)
sorted_desc = np.sort(arr)[::-1]
print(sorted)
print(sorted_desc)

[1 4 5]
[5 4 1]


In [83]:
scores = np.array([
    [78, 85, 62, 90],
    [56, 45, 70, 60],
    [88, 92, 81, 77],
    [40, 55, 58, 65],
    [95, 89, 93, 91]
])
mask = np.mean(scores, axis = 1) > 75
over_75 = scores[mask]
one_and_three = over_75[:,[1,3]]
print(one_and_three)

[[85 90]
 [92 77]
 [89 91]]
