# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
a = np.arange(1,17)
b = a.reshape(4,4)
c = np.pad(b, pad_width=1, mode='constant', constant_values=0)
print(c)

[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  0]
 [ 0  5  6  7  8  0]
 [ 0  9 10 11 12  0]
 [ 0 13 14 15 16  0]
 [ 0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [12]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
d = np.diag([1,2,3,4],k = -1)
print(d)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [25]:
e = np.zeros((8,8))
e[1::2, ::2] = 1
e[::2, 1::2] = 1
print(e)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
f = np.random.randint(0,10,(6,7,8))
g = f.shape
h = np.unravel_index(99,g)
print(h)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [45]:
i = np.array([[0,1],[1,0]])
j = np.tile(i,(4,4))
print(j)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [3]:
k= np.random.randint(0,10,(5,5))

min = np.min(k)
max = np.max(k)

l = (k - min) / (max - min)

print(k)
print(l)


[[6 1 6 6 0]
 [8 4 4 8 4]
 [3 9 5 0 6]
 [7 0 5 9 1]
 [3 2 1 7 8]]
[[0.66666667 0.11111111 0.66666667 0.66666667 0.        ]
 [0.88888889 0.44444444 0.44444444 0.88888889 0.44444444]
 [0.33333333 1.         0.55555556 0.         0.66666667]
 [0.77777778 0.         0.55555556 1.         0.11111111]
 [0.33333333 0.22222222 0.11111111 0.77777778 0.88888889]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [30]:
m = np.dtype([
    ('r', np.uint8), 
    ('g', np.uint8), 
    ('b', np.uint8), 
    ('a', np.uint8)
])

n = np.array((200, 100, 150, 50), dtype=m)

print(n)

(200, 100, 150, 50)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
o = np.random.randint(0,5,(5,3))
p = np.random.randint(0,5,(3,2))

np.dot(o,p)

[[2 2 4]
 [1 1 0]
 [2 4 0]
 [1 3 0]
 [2 1 1]]
[[2 3]
 [4 1]
 [0 0]]


array([[12,  8],
       [ 6,  4],
       [20, 10],
       [14,  6],
       [ 8,  7]], dtype=int32)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [45]:
q = np.arange(11)
q[2:9] *= -1

print(q)

[ 0  1 -2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [46]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([1,2,3,4,5,6,7,8,9])
z**z # Legal
2 << z >> 2 # Legal
z < - z # Legal
1j * z # Legal
z/1/1 # Legal
z <z> z # Illgeal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
#np.array(0) / np.array(0) # Runtime warning np.float64(nan)
#np.array(0) // np.array(0) # Divide by zero in floor divide np.int64(0)
np.array([np.nan]).astype(int).astype(float) # Invalid value in cast array([-9.22337204e+18])

C:\Users\victo\AppData\Local\Temp\ipykernel_30704\4098155013.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) # Invalid value in cast array([-9.22337204e+18])


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [60]:
r = np.array([.45, 2.9,0.6,1.5]) 
np.round(r,1)


array([0.4, 2.9, 0.6, 1.5])

#### 30. How to find common values between two arrays? (★☆☆)

In [77]:
s = np.array([1,2,3,4,5,6])
t = np.array([3,4,5,6,7,8])

np.intersect1d(s,t)

array([3, 4, 5, 6])